CREATE TABLE CAD_HIDROMETRO
(
	ID_HIDROMETRO INT IDENTITY(1,1),
	HIDROMETRO VARCHAR(MAX) NOT NULL
	
	CONSTRAINT pk_hidrometro PRIMARY KEY (ID_HIDROMETRO),
	CONSTRAINT un_hidrometro UNIQUE (HIDROMETRO)	
)