CREATE TABLE CLIENTE
(
	COD_CLIENTE INT IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	CPFOUCNPJ INT,
	CPF_CNPJ VARCHAR(14), 
	IDENT VARCHAR(MAX),
	EMAIL VARCHAR(MAX),
	TEL_FIXO VARCHAR(11),
	TEL_CELULAR VARCHAR(11),
	TEL_RECADO VARCHAR(11),
	RESP_RECADO VARCHAR(100),
	
	CONSTRAINT pk_cliente PRIMARY KEY (COD_CLIENTE),
	CONSTRAINT un_cliente UNIQUE(CPF_CNPJ)
	
)