CREATE TABLE CONFIG_GERAL
(
	ID_CONFIG_GERAL INT IDENTITY(1,1),
	COND_REGIAO INT NOT NULL, 
	DIA_LEITURA INT NOT NULL,
	MES_LEITURA INT NOT NULL,
	ANO_LEITURA INT NOT NULL,
	DIA_VENCIMENTO INT NOT NULL,
	MES_VENCIMENTO INT NOT NULL,
	ANO_VENCIMENTO INT NOT NULL,
	JUROS FLOAT,
	MULTA FLOAT,
	TEXTO_CONTA VARCHAR(MAX) NOT NULL,
	
	CONSTRAINT pk_config PRIMARY KEY (ID_CONFIG_GERAL)	
)