CREATE TABLE CONFIG_GERAL_OLD
(
	ID_CONFIG_GERAL INT IDENTITY(1,1),
	DIA_LEITURA INT NOT NULL,
	MES_LEITURA INT NOT NULL,
	ANO_LEITURA INT NOT NULL,
	DIA_VENCIMENTO INT NOT NULL,
	MES_VENCIMENTO INT NOT NULL,
	ANO_VENCIMENTO INT NOT NULL,
	JUROS FLOAT,
	MULTA FLOAT,
	TEXTO_CONTA VARCHAR(MAX) NOT NULL,
	
	CONSTRAINT pk_config_old PRIMARY KEY (ID_CONFIG_GERAL)	
)