CREATE TABLE CONTA
(
	ID_CONTA INT IDENTITY(1,1),
	COD_CLIENTE INT NOT NULL,
	HIDROMETRO VARCHAR(MAX) NOT NULL,
	MES INT,
	ANO INT, 
	DT_LEITURA DATE,
	DT_VENCIMENTO DATE,
	LEITURA_ANTERIOR INT,
	LEITURA_ATUAL INT,
	CONSUMO INT,
	TOTAL FLOAT,
	
	CONSTRAINT pk_conta PRIMARY KEY (ID_CONTA),
	CONSTRAINT fk_conta_instalacao FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
	CONSTRAINT un_conta UNIQUE(HIDROMETRO, MES, ANO)
	
)