CREATE TABLE DADOS_CONTA
(
	ID_DADOS_CONTA INT IDENTITY(1,1),
	COD_CLIENTE INT NOT NULL,
	HIDROMETRO VARCHAR(MAX) NOT NULL,
	MES INT,
	ANO INT,
	DESCRICAO VARCHAR(MAX),
	VALOR FLOAT,
	
	CONSTRAINT pk_conta PRIMARY KEY (ID_DADOS_CONTA),
	CONSTRAINT fk_conta_instalacao FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
	CONSTRAINT fk_hidrometro FOREIGN KEY (HIDROMETRO) REFERENCES CAD_HIDROMETRO (HIDROMETRO),
	CONSTRAINT un_dados_conta UNIQUE(COD_CLIENTE, HIDROMETRO, MES, ANO, DESCRICAO)
	
)