Cadastro
	CODIGO DO CLIENTE
	NOME DO CLIENTE
	CPF OU CNPJ
	IDENTIDADE
	EMAIL
	TELEFONE FIXO
	TELEFONE CELULAR
	RECADOS
	RESPONSAVEL


CREATE TABLE END_COBRANCA
(
	ID_END_COB INT IDENTITY(1,1),
	COD_CLIENTE INT,
	ENDERECO VARCHAR(MAX) NOT NULL,
	NUMERO INT,
	COMPLEMENTO VARCHAR(MAX), 
	BAIRRO VARCHAR(MAX),
	CIDADE VARCHAR(MAX),
	SIG_UF VARCHAR(2),
	CEP VARCHAR(10),
	
	CONSTRAINT pk_end_cob PRIMARY KEY (ID_END_COB),
	CONSTRAINT fk_end_cliente FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
	
	
)