CREATE TABLE END_INSTALACAO
(
	ID_END_INST INT IDENTITY(1,1),
	COD_CLIENTE INT,
	HIDROMETRO VARCHAR(MAX) NOT NULL,
	ENDERECO VARCHAR(MAX) NOT NULL,
	GLEBA VARCHAR(MAX),
	CHACARA VARCHAR(MAX), 
	UNID_CONSUMO VARCHAR(MAX) NOT NULL,
	CIDADE VARCHAR(MAX) NOT NULL,
	SIG_UF VARCHAR(2),
	TEL_CELULAR VARCHAR(11),
	DT_ATIVACAO DATETIME,
	DT_DESATIVACAO DATETIME,
	
	CONSTRAINT pk_end_inst PRIMARY KEY (ID_END_INST),
	CONSTRAINT fk_inst_cliente FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
	
)